# Base image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY . .

# Build the TypeScript code if needed
RUN npm run build

# Expose the service port
EXPOSE 8006

# Run the service
CMD ["npm", "start"]
