# Base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code if necessary
RUN npm run build

# Expose the API Gateway port
EXPOSE 3000

# Run the API Gateway
CMD ["npm", "run", "dev"]