services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - finance-net

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - finance-net
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - finance-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finance-net
    environment:
      RABBITMQ_LISTENER_TCP: "0.0.0.0"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - expense
      - reporting

  user:
    build:
      context: ./services/user
      dockerfile: dockerfile.dev
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgres://admin:password@db:5432/user
    volumes:
      - ./services/user:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db

  expense:
    build:
      context: ./services/expense
      dockerfile: dockerfile.dev
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=postgres://admin:password@db:5432/expense
    volumes:
      - ./services/expense:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db
      - rabbitmq

  reporting:
    build:
      context: ./services/reporting
      dockerfile: dockerfile.dev
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - DATABASE_URL=postgres://admin:password@db:5432/reporting
    volumes:
      - ./services/reporting:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db
      - rabbitmq

  income:
    build:
      context: ./services/income
      dockerfile: dockerfile.dev
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - DATABASE_URL=postgres://admin:password@db:5432/income
    volumes:
      - ./services/income:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db
      - rabbitmq

volumes:
  mongo_data:
  pgdata:

networks:
  finance-net:
    driver: bridge