services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - finance-net

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - finance-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finance-net
    environment:
      RABBITMQ_LISTENER_TCP: "0.0.0.0"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - transaction
      - reporting

  user:
    build:
      context: ./services/user
      dockerfile: dockerfile.dev
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgres://postgres:example@db/user
    volumes:
      - ./services/user:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db

  reporting:
    build:
      context: ./services/reporting
      dockerfile: dockerfile.dev
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - DATABASE_URL=postgres://postgres:example@db/reporting
    volumes:
      - ./services/reporting:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db
      - rabbitmq

  transaction:
    build:
      context: ./services/transaction
      dockerfile: dockerfile.dev
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - DATABASE_URL=postgres://postgres:example@db/transaction
    volumes:
      - ./services/transaction:/app
      - /app/node_modules
    networks:
      - finance-net
    depends_on:
      - db
      - rabbitmq

volumes:
  mongo_data:
  pgdata:

networks:
  finance-net:
    driver: bridge