# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY . .

# Expose the service port
EXPOSE 8002

# Run the service
CMD ["npm", "run", "dev"]
