# Base image
FROM node:22

# Install OpenSSL
RUN apt-get update -y
RUN apt-get install -y openssl

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY . .

# Prisma generate
RUN npx prisma generate

# Build the TypeScript code if needed
RUN npm run build

# Expose the service port
EXPOSE 8001

# Run the service
CMD ["npm", "start"]
