name: Test

on:
  push:
    branches:
    - main
    paths:
    - frontend/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set-up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - uses: actions/cache@v4
      id: npm-cache
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependancies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      working-directory: frontend
      run: npm ci

    - name: Test
      working-directory: frontend
      run: CI=true npm test